### ISSUE TITLE
Please add path prefix functionality

### ISSUE THREAD

**Issue by DirkTheDaring** [kevana/ui-for-docker#236] opened 2016-08-13 13:14 UTC
I'd like to run dockerui under a path prefix, like "http://mydomain/dockerui"

it would be great if i this could be set somewhere   like "--path-prefix=/dockerui"  or via environment variable "PATH_PREFIX=/dockerui"

**Comment by deviantony** [comment] 2016-08-13 20:53
Duplicate of #97

**Closed by deviantony** 2016-08-13 20:53 UTC
