### ISSUE TITLE
subfolder in url breaks fonts

### ISSUE THREAD

**Issue by jlec** [kevana/ui-for-docker#232] opened 2016-08-03 08:02 UTC
I am serving dockui from a subdirectory like example.com/dockerui which results in 

```
https://example.com/fonts/glyphicons-halflings-regular.woff Failed to load resource: the server responded with a status of 404 ()
https://example.com/fonts/glyphicons-halflings-regular.ttf Failed to load resource: the server responded with a status of 404 ()
```

Everything else works fine. Without a subdirectory also the fonts are working fine.

**Comment by deviantony** [comment] 2016-08-03 09:07
Duplicate of #97

**Closed by deviantony** 2016-08-03 09:07 UTC
