### ISSUE TITLE
Can not start container?

### ISSUE THREAD

**Issue by Tairy** [kevana/ui-for-docker#240] opened 2016-08-23 10:35 UTC
I got this error when I want to start a container by web ui:

`starting container with HostConfig was deprecated since v1.10 and removed in v1.12`

This is my docker info:

```
API Endpoint: dockerapi
API Version: 1.24
Docker version: 1.12.0
Git Commit: 8eab29e
Go Version: go1.6.3
```

I want to config binds and links, so what shoud i do to solve this problam.

Thanks you for reading.

**Comment by linquize** [comment] 2016-08-23 10:38
Docker 1.12 #234 ?

**Comment by Tairy** [comment] 2016-08-23 10:46
@linquize Yes, my docker version is 1.12.0, and I found [here] (http://docs.master.dockerproject.org/engine/reference/api/docker_remote_api/#/v1-24-api-changes)  said: 

> POST /containers/(id or name)/start no longer accepts a HostConfig.

So I want to know how to fix it and config binds and links. 

Thanks!

**Comment by deviantony** [comment] 2016-08-23 21:09
Docker 1.12 is not fully supported yet.

Duplicate of #234

**Closed by deviantony** 2016-08-23 21:09 UTC
